[package]
name = "keepass"
version = "0.1.0"
authors = ["Stefan Seemayer <stefan@seemayer.de>"]
license = "MIT"

[dependencies]
byteorder = "^0.4.2"
flate2 = "^0.2.13"
rust-crypto = "^0.2.34"
secstr = "^0.2.1"
xml-rs = "^0.3.0"
rustc-serialize = "^0.3.16"
